<#
.SYNOPSIS
    Registers Orion's background interfaces as Windows Scheduled Tasks that
    start automatically at logon and restart themselves on failure -- the
    Windows equivalent of the systemd/*.service units used on Linux/Raspberry
    Pi (see README.md section 8).

.DESCRIPTION
    Each interface (web HUD, Telegram bot, always-listening voice loop)
    becomes its own task: Orion-Web, Orion-Telegram, Orion-Voice. They run as
    the user who registers them, only while that user is logged on (a
    personal-laptop assumption -- this is not meant to run headless as SYSTEM).
    core/config.py's load_dotenv() finds .env from the working directory the
    task sets, so there's no separate "EnvironmentFile=" step like on Linux.

    Safe to re-run after `git pull` or editing .env -- Register-ScheduledTask
    overwrites an existing task of the same name instead of erroring.

.PARAMETER Interfaces
    Which interfaces to register. Defaults to all three. Pass a subset if you
    only want e.g. the web HUD: -Interfaces web

.EXAMPLE
    .\scripts\windows\install_orion_tasks.ps1
.EXAMPLE
    .\scripts\windows\install_orion_tasks.ps1 -Interfaces web,telegram
#>

param(
    [ValidateSet("web", "telegram", "voice")]
    [string[]]$Interfaces = @("web", "telegram", "voice")
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path

# pythonw.exe (no console window flashing up at every logon) if the venv has
# it -- every venv created from a standard python.org install does -- else
# fall back to python.exe so this still works rather than hard-erroring.
$PythonExe = Join-Path $RepoRoot ".venv\Scripts\pythonw.exe"
if (-not (Test-Path $PythonExe)) {
    $PythonExe = Join-Path $RepoRoot ".venv\Scripts\python.exe"
}
if (-not (Test-Path $PythonExe)) {
    throw "Can't find a venv Python under $RepoRoot\.venv\Scripts\. Create it first (README section 1): " +
          "python -m venv .venv; .venv\Scripts\Activate.ps1; pip install -r requirements.txt"
}

$Modules = @{
    web      = "interfaces.web.app"
    telegram = "interfaces.telegram_bot"
    voice    = "interfaces.voice.voice_loop"
}

# Task Scheduler's nearest equivalent to systemd's Restart=on-failure /
# RestartSec=5: retry up to 999 times, once a minute. IgnoreNew stops a
# second copy piling up if the logon trigger fires while a manually-started
# instance is already running. ExecutionTimeLimit of zero means "never
# time out" -- these are meant to run indefinitely, not as a one-shot job.
$RestartSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0)

# Only fire when the user running this script logs on -- not any account on
# a shared machine.
$Trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

foreach ($name in $Interfaces) {
    $taskName = "Orion-" + (Get-Culture).TextInfo.ToTitleCase($name)
    $action = New-ScheduledTaskAction -Execute $PythonExe -Argument "-m $($Modules[$name])" -WorkingDirectory $RepoRoot

    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $Trigger `
        -Settings $RestartSettings `
        -Description "Orion $name interface (auto-generated by install_orion_tasks.ps1 -- see systemd/orion-$name.service for the Linux equivalent)" `
        -Force | Out-Null

    Write-Host "Registered '$taskName' -- starts at your next logon, or right now: Start-ScheduledTask -TaskName '$taskName'"
}

Write-Host ""
Write-Host "Manage from Task Scheduler (taskschd.msc, under Task Scheduler Library) or PowerShell:"
Write-Host "  Get-ScheduledTask -TaskName 'Orion-*'"
Write-Host "  Get-ScheduledTaskInfo -TaskName 'Orion-Web'    # last run time/result"
Write-Host "  Start-ScheduledTask -TaskName 'Orion-Web'"
Write-Host "  Stop-ScheduledTask -TaskName 'Orion-Web'"
Write-Host "  .\scripts\windows\uninstall_orion_tasks.ps1    # remove all three"
